"""add soft delete to categories and suppliers

Revision ID: 9f15a6a3363d
Revises: 51da2109bb98
Create Date: 2026-09-15 11:16:15.855992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f15a6a3363d'
down_revision: Union[str, Sequence[str], None] = '51da2109bb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
